# Generated by Django 4.0 on 2021-12-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('poster', models.ImageField(default='games/posters/default.jpg', upload_to='games/posters/')),
                ('release_date', models.DateField(blank=True)),
                ('is_cracked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('horror', 'Horror'), ('shooter', 'Shooter'), ('adventure', 'Adventure'), ('sci-fi', 'Sci-fi')], default='horror', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pc', 'PC'), ('playstation', 'Playstation'), ('xbox', 'Xbox')], default='pc', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(default='games/images/default.jpg', upload_to='games/images/')),
                ('description', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('developer', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name_plural': 'Games Detail',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='games.Platform'),
        ),
    ]
