# Generated by Django 4.0 on 2021-12-20 16:22

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='games/default.jpg', upload_to=games.models.upload_to, verbose_name='Image')),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('developer', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.genre')),
            ],
        ),
    ]
