# Generated by Django 4.0 on 2021-12-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='games/images/default.jpg', upload_to='games/images/')),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('developer', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
