# Generated by Django 4.0 on 2021-12-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedetail',
            old_name='game_id',
            new_name='game',
        ),
    ]
