# Generated by Django 4.0 on 2021-12-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_options_gamedetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamedetail',
            options={'verbose_name_plural': 'Games Detail'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
