# Generated by Django 4.0 on 2021-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_game_id_gamedetail_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='slug',
            field=models.SlugField(default='game_slug', max_length=250),
        ),
    ]
