# Generated by Django 4.0 on 2022-01-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
