# Generated by Django 4.0 on 2021-12-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamedetail_options_remove_game_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_cracked',
            field=models.BooleanField(default=False),
        ),
    ]
