# Generated by Django 4.0 on 2022-01-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_favorites'),
        ('games', '0003_rename_platform_game_platforms_usergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
    ]
