# Generated by Django 4.0 on 2021-12-28 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gamedetail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='release_date',
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('playstation', 'Plstation'), ('xbox', 'Xbox')], default='pc', max_length=15),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('horror', 'Horror'), ('shooter', 'Shooter'), ('adventure', 'Adventure'), ('sci-fi', 'Sci-fi')], default='horror', max_length=100),
        ),
    ]
