# Generated by Django 4.0 on 2021-12-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_is_cracked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedetail',
            old_name='game',
            new_name='game_id',
        ),
    ]
