# Generated by Django 4.0 on 2022-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_usergame_favorite_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, to='games.Game'),
        ),
    ]
