# Generated by Django 4.0 on 2022-01-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_usergame_favorite_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGame',
        ),
    ]
