# Generated by Django 4.0 on 2021-12-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_gamedetail_release_date_game_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('playstation', 'Playstation'), ('xbox', 'Xbox')], default='pc', max_length=15),
        ),
    ]
