# Generated by Django 4.0 on 2021-12-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_game_gamedetail_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_image', models.ImageField(upload_to='web_posters/%Y/%m/%d')),
            ],
        ),
    ]
