# Generated by Django 4.0 on 2021-12-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_webposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webposter',
            name='web_image',
            field=models.FileField(upload_to='web_posters/'),
        ),
    ]
