# Generated by Django 4.0 on 2022-03-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_usergame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_cracked',
        ),
    ]
