<<<<<<< HEAD
# Generated by Django 4.0 on 2021-12-26 18:58
=======
# Generated by Django 4.0 on 2021-12-26 09:38
>>>>>>> 7a740013111210c2888369234187385d34706d11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_webposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webposter',
            name='web_image',
<<<<<<< HEAD
            field=models.ImageField(upload_to='web_posters/'),
=======
            field=models.FileField(upload_to='web_posters/'),
>>>>>>> 7a740013111210c2888369234187385d34706d11
        ),
    ]
