# Generated by Django 4.0 on 2022-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_engine_name_alter_mode_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_engines',
            field=models.ManyToManyField(blank=True, to='games.Engine'),
        ),
    ]
