# Generated by Django 4.0 on 2022-01-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='games.Game'),
        ),
    ]
